# === GitHub Actions: Continuous Integration for FIM ==========================
# Triggers: run on every push and pull request to any branch.
name: CI

on:
  push:
  pull_request:

jobs:
  test:
    # Use the latest Ubuntu runner. (You can pin to a specific version if desired.)
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository code
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Provision Python 3.12 (matches your Dockerfile & local setup)
      #    The 'cache: pip' line speeds up installs across runs.
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      # 3) Install dependencies for tests
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      # 4) Run the unit tests quietly (-q). Failures will fail the job.
      - name: Run tests
        run: pytest -q
